name: Python Test and Build Package

on: [ push ]

jobs:
  test:
    runs-on: self-hosted
    container:
      image: mzandtheraspberrypi/my-bittle-build-arm64:2024-01-21
      options: --cpus 1
    steps:
      - name: check_version
        run: |
          python3 --version
      - name: check_libraries
        run: |
          python3 -m pip freeze
      - name: checkout_repo
        uses: actions/checkout@v2.3.4
      - name: check_workspace_loc
        run: |
          echo ${GITHUB_WORKSPACE}
      - name: check_workspace_contents
        run: |
          ls -l ${GITHUB_WORKSPACE}
      - name: test
        run: |
          python3 -m unittest discover
  build:
    needs: test
    runs-on: self-hosted
    container:
      image: mzandtheraspberrypi/my-bittle-build-arm64:2024-01-21
      options: --cpus 1
    steps:
      - name: checkout_repo
        uses: actions/checkout@v2.3.4
      - name: build
        run: |
          python3 -m build
      - name: archive_artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: |
            dist